apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - image: local/spring-music-mongodb
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: music_data
        - mountPath: /data/configdb
          name: music_data
      restartPolicy: Always
      volumes:
      - name: music_data
        persistentVolumeClaim:
          claimName: music_data
      - name: music_data
        persistentVolumeClaim:
          claimName: music_data
status: {}
