apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mysql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: reschedule
          value: on-node-failure
        - name: MYSQL_ROOT_PASSWORD
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: socksdb
        image: local/spring-music-mysql
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
