apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spring-music-3
  name: spring-music-3
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8080
  selector:
    io.kompose.service: spring-music-3
status:
  loadBalancer: {}
