apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spring-music-services-1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spring-music-services-1
    spec:
      containers:
      - image: local/spring-music-services
        name: spring-music-services-1
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
