apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spring-music-2
  name: spring-music-2
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8080
  selector:
    io.kompose.service: spring-music-2
status:
  loadBalancer: {}
