apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spring-music-services-1
  name: spring-music-services-1
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8081
  selector:
    io.kompose.service: spring-music-services-1
status:
  loadBalancer: {}
