apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: streams
  name: streams
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  - name: "9092"
    port: 9092
    targetPort: 9002
  selector:
    io.kompose.service: streams
status:
  loadBalancer: {}
